  
  

/* THIS FILE IS GENERATED BY T4 TEMPLATE. DO NOT MAKE ANY MANUAL CODE CHANGES HERE.				*/
/* If the content of this file has to be actualized,  run corresponded .TT file (Text Template)	*/
/* It will re-scan the folder with Ledger Test files and create a new set of unit tests.		*/
using Microsoft.VisualStudio.TestTools.UnitTesting;
namespace NLedger.IntegrationTests
{
    [TestClass]
    [DeploymentItem(@"test\nledger", @"test\nledger")]
    public class TestSet1_test_nledger
    {
		
        [TestMethod]
        [TestCategory("Integration")]
        public void IntegrationTest_test_nledger_opt_download()
        {
            new TestRunner(@"test\nledger\opt-download.test").Run();
        }
		
    }
}
